worker_processes  1;

events {
    worker_connections  1024;
}

stream {
    upstream workers {
        server 127.0.0.1:5001;
        server 127.0.0.1:5002;
    }

    server {
        listen 5000;
        proxy_pass workers;
    }
}
